public enum FileProcessingEvent {
    READER_STARTED,
    READER_FINISHED,
    PROCESSOR_STARTED,
    PROCESSOR_FINISHED,
    WRITER_STARTED,
    WRITER_FINISHED,
    LINE_READ,
    LINE_PROCESSED,
    LINE_WRITTEN,
    PROCESSING_COMPLETED
}
